### ISSUE TITLE
(root) Additional property name is not allowed (PHPUNIT runner)

### ISSUE THREAD

**Issue by julienloizelet** [php-perfect/ddev-intellij-plugin#100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you sure that this bug is related to this DDEV Integration Plugin?

- [ ] I am sure

### Describe the bug

Hi,
I followed the instruction [here](https://ddev.readthedocs.io/en/latest/users/topics/phpstorm/) to test the plugin with phpunit.

When I want to run the phpunit tests, (`Run the runner that you created.` part), I've got the following error message   :

```
[docker-compose://[/some-path/.ddev/.ddev-docker-compose-full.yaml]:web/]:php7.4 /var/www/html/some-other-path/vendor/phpunit/phpunit/phpunit --no-configuration /var/www/html/some-other-path/tests/Integration --teamcity --cache-result-file=/var/www/html/.phpunit.result.cache
Testing started at 11:06 ...
(root) Additional property name is not allowed

Process finished with exit code 15
```

If I edit the `/.ddev-docker-compose-full.yaml` file and remove the top level `name` entry (`name: ddev-php74`), the error disappears.

### Steps to reproduce

1. Install the plugin
2. Follow the instructions [here](https://ddev.readthedocs.io/en/latest/users/topics/phpstorm/#enabling-phpunit) to configure phpunit
3. Run the runner

### Additional context

I am not sure whether this is related to the DDEV plugin or to DDEV itself.
I am running DDEV 1.21.1 on PHPSTORM 2022.2 (on Ubuntu 18.04)

**Comment by rfay** [comment]
DDEV v1.21.1 adds the `name` element to make things easier in the future for this plugin.

But you may be using an old docker-compose version? 

See 

* https://github.com/php-perfect/ddev-intellij-plugin/issues/95

If you'll set the docker-compose binary to the one provided by DDEV I think your problem will go away.

**Comment by julienloizelet** [comment]
> DDEV v1.21.1 adds the `name` element to make things easier in the future for this plugin.
> 
> But you may be using an old docker-compose version?
> 
> See
> 
>     * [Use ~/.ddev/bin/docker-compose as the docker-compose tool in Tools->Docker #95](https://github.com/php-perfect/ddev-intellij-plugin/issues/95)
> 
> 
> If you'll set the docker-compose binary to the one provided by DDEV I think your problem will go away.

indeed, if I modify the `Docker compose executable` path to point to ` ~/.ddev/bin/docker-compose`, there is no more error.

I guess this issue can be closed. 

Thanks @rfay

**Comment by rfay** [comment]
You probably have docker-compose v1 in your $PATH, `docker-compose --version` will tell you. If you use Docker Desktop, you can probably also fix this with changing to docker-compose v2 in the Docker Desktop settings.

**Comment by rfay** [comment]
I guess I had hoped we could solve this with 

* #95 
but it wasn't accepted. I think it should be reconsidered.

However, this PR to DDEV docs may help:

* https://github.com/drud/ddev/pull/4157

**Comment by julienloizelet** [comment]
> You probably have docker-compose v1 in your $PATH, `docker-compose --version` will tell you. If you use Docker Desktop, you can probably also fix this with changing to docker-compose v2 in the Docker Desktop settings.

For information, `docker-compose --version` returns  `v2.1.1` (and I'm not using Docker Desktop).

**Comment by nico-loeber** [comment]
@julienloizelet, please make sure to enable docker compose v2 support in PHPStorm (`File | Settings | Build, Execution, Deployment | Docker | Tools`).

![image](https://user-images.githubusercontent.com/18308418/188006810-07b9ff74-8491-4d7c-b07a-35e7a98611c4.png)

Please note that no manual configuration is required for running tests in ddev when using the plugin.
You can just click the play button beside a test method if your phpunit.xml is configured correctly.

**Comment by nico-loeber** [comment]
It makes a difference when using the docker compose binary provided by docker desktop. I had trouble when I had compose v2 support enabled in docker desktop, but not in PHPStorm when importing the docker-compose.yml created by ddev (with compose v2 syntax).
