### ISSUE TITLE
DDEV config not recognized from subfolders

### ISSUE THREAD

**Issue by Dergell** [php-perfect/ddev-intellij-plugin#104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you sure that this bug is related to this DDEV Integration Plugin?

- [X] I am sure

### Describe the bug

I have a project running on Windows 10 WSL2 Ubuntu with DDEV. Everything is working fine from the terminal, but the DDEV Integration Plugin does not recognize the existing config, because it is in a subfolder.

In this project, there are several basic configuration files that are not part of DDEV itself. These files all reside in the git root folder. Then there's a folder `www` which contains a Magento 2 setup including the `.ddev` folder. When I select Tools > DDEV > Configure it will create a new `.ddev` folder in the project root above `www`.

![Screenshot 2022-09-07 151648](https://user-images.githubusercontent.com/46611394/188888079-228908cb-5b17-45d0-b841-a814413a1cf1.jpg)

It would be nice if the plugin could either detect DDEV configurations in subfolders or would allow a config setting in PhpStorm where I can define the folder the plugin should look into.

**Comment by nico-loeber** [comment]
Hey @Dergell,

this is the expected behavior.

If you got a mono repo and www is the actual root of the project you would like to work on, please open this folder as a project in phpstorm.
The ddev config is expected to be at the project root, same as a composer.json for example.
