### ISSUE TITLE
Autoconfigured data source DSN not compatible to MariaDB Connector/J v3

### ISSUE THREAD

**Issue by dahaupt** [php-perfect/ddev-intellij-plugin#106]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you sure that this bug is related to this DDEV Integration Plugin?

- [X] I am sure

### Describe the bug

The autoconfigured data source can not establish a connection.

**Error message:** Incorrect driver and/or database URL specified.

Related documentation: [jdbc:mysql scheme compatibility](https://mariadb.com/kb/en/about-mariadb-connector-j/#jdbcmysql-scheme-compatibility)

### Additional context

**Data Source URL:** jdbc:mysql://127.0.0.1:49156/db?user=db&password=db
**MariaDB Connector/J:** v3.0.7
**PhpStorm:** 2022.2.2 RC
**DDEV:** v1.21.1

**Comment by nico-loeber** [comment]
Hey @dahaupt,

thank you for reporting this issue!

I've fixed this in https://github.com/php-perfect/ddev-intellij-plugin/commit/0534375af67771ccb7341f94b3f9f6db572dea79.
The fix will be included in the next release of the plugin.
