### ISSUE TITLE
Not compatible with PHPStorm 223 (2022.3 Beta)

### ISSUE THREAD

**Issue by Schrank** [php-perfect/ddev-intellij-plugin#129]
### Describe the bug

Trying to install the plugin on the current EAP, but unfortunately it is not compatible :-(

PhpStorm 2022.3 Beta
Build #PS-223.7571.15, built on November 10, 2022
Licensed to PhpStorm EAP user: Fabian Blechschmidt
Expiration date: December 10, 2022
Runtime version: 17.0.5+1-b653.12 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.6.1
GC: G1 Young Generation, G1 Old Generation
Memory: 6144M
Cores: 10
Metal Rendering is ON
Registry:
    debugger.watches.in.variables=false
    run.processes.with.pty=TRUE
    ide.balloon.shadow.size=0
    php.brace.alt.syntax=true

### Steps to reproduce

1. Get current EAP: https://www.jetbrains.com/phpstorm/nextversion/
2. Install it
3. Download plugin https://plugins.jetbrains.com/plugin/18813-ddev-integration
4. try to install it
5. Get error:
6. ```Plugin 'DDEV Integration' (version '1.0.3') is not compatible with the current version of the IDE, because it requires build 222.* or older but the current build is PS-223.7571.15```

**Comment by Schrank** [comment]
Happy to test! :-)If you need any other help, tell me. Short on time, but giving my best

**Comment by nico-loeber** [comment]
Just to give a small update. We started working on the compatbility for version 22.3 of the IDE.
I have to admint that I missed the some of the required changes in the EAP changelogs, so I am a bit late.

Sadly there is currently an Issue that is blocking development:
* https://github.com/JetBrains/gradle-intellij-plugin/issues/1239

We plan to provide EAP Versions of the plugin that will support EAP Versions of the IDE.

**Comment by nico-loeber** [comment]
I have just released version 1.0.4 of the plugin. This version will now support PHPStorm 2022.3. Please note that it may take up to two days for the version to go through the JetBrains review process.
Since I would like to support EAP/Beta versions, I will leave this issue open for now until an appropriate workflow is implemented.

@Schrank, you can download the plugin here https://github.com/php-perfect/ddev-intellij-plugin/releases/tag/1.0.4 or wait till it passes the review process and is available in your IDE for automatic update.

**Comment by rfay** [comment]
This still hasn't shown up in the marketplace, but I was able to follow the instructions and download and it seems to be working great. I did have to load it twice, maybe some kind of PhpStorm bug. First time it removed the old version, second time it installed it. (macOS Ventura, PhpStorm 2022.3)

**Comment by nico-loeber** [comment]
Yes, the review by JetBrains is a manual process I think. At leas there are no reviews at weekend. 
It's not available for download in the marketplace and the IDE.
The behavior you are describing sounds like a IntelliJ related issue. I don't think there is much I can change regarding the installation / update behavior.

**Comment by Morgy93** [comment]
Just got the update via plugin manager:

<img width="656" alt="image" src="https://user-images.githubusercontent.com/7961978/207300182-f85e5ed2-b503-404a-9d31-c9e474d4b18b.png">

It seems to work for the things I used it for. Thanks for the effort ❤️

**Comment by M-arcus** [comment]
The plugin update to 1.0.4 seems to be working well in 2022.3, even a restart was not required.

**Comment by JCL324** [comment]
I just tried 1.0.4, had upgraded to PHPStorm 2022.3 earlier and now today upgraded to MacOS Ventura. Nothing seems to work :( The Tools menu does have DDEV at the bottom but all the items are disabled. And the option in Terminal to start a new DDEV SSH sesh is missing too. Any ideas to try?

**Comment by rfay** [comment]
It's been working fine for me, I would recommend removing the plugin and then adding it in again.

**Comment by JCL324** [comment]
Randy, just did all that, restarted, etc. Same result. 

Edit: OMG! DDEV is not installed! I had just done a brew upgrade and noticed 1.21.3 -> 1.21.4 was out but the brew install is apparently not completing correctly. I also wondered why I was getting this "bash: /opt/homebrew/etc/bash_completion.d/ddev: No such file or directory".

**Comment by rfay** [comment]
Glad you got it figured out!

**Comment by rfay** [comment]
Not sure why I have privileges to close this, but I think it's done and will close. I'm sure @nico-loeber will respond to anything else that needs to be dealt with or any additional comments.

**Comment by JCL324** [comment]
Thanks Randy, I got Xcode updated, brew is happy now and so is DDEV. Confirming this plugin works as expected :)
