### ISSUE TITLE
Schema validation is missing project type "craftcms"

### ISSUE THREAD

**Issue by jamesmacwhite** [php-perfect/ddev-intellij-plugin#141]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you sure that this bug is related to this DDEV Integration Plugin?

- [X] I am sure

### Describe the bug

When using the project type of "craftcms" the schema validation does not recognise the option as it is missing in the spec.

![image](https://user-images.githubusercontent.com/8067792/209954982-2616c92a-7d44-4314-87e4-222aa56c9cea.png)

The `craftcms` project type is more recent and it looks like the schema data is from DDEV 1.19 which pre dates the addition.

### Steps to reproduce

1. Create DDEV `config.yaml` using project type "craftcms"
2. Install DDEV integration plugin
3. PHPStorm will show a schema validation error with the project type.

**Comment by jamesmacwhite** [comment]
For reference the project type of `craftcms` is valid from DDEV 1.21.2 and above.

**Comment by nico-loeber** [comment]
Thanks for reporting @jamesmacwhite!

The plan was to place the schema in the ddev repository so the schema is released together with ddev and can be downloaded from github in the version needed for your ddev installation.

As this was a bit too complex for the launch I just out the schema of the at this date current version in the plugin itself:
https://github.com/php-perfect/ddev-intellij-plugin/blob/main/src/main/resources/schema/ddev-config-1.19.schema.json

If you like you can create a pull request to add the schema for 1.21.
To load it the version number number has to be determined dynamically in 
https://github.com/php-perfect/ddev-intellij-plugin/blob/main/src/main/java/de/php_perfect/intellij/ddev/config/ConfigJsonSchemaProviderFactory.java

I will try to find a long term solution for this, as I don't like to create new releases of the plugin for ddev configuration changes.

**Comment by jamesmacwhite** [comment]
@nico-loeber Thanks for acknowledging this. I have very little Java experience in terms of the loading of the correct schema, but I'm happy to generate a schema JSON file with the latest parameters.

The issue I guess is the schema for 1.19, 1.20, 1.21 etc will also differ between incremental releases, so in this example, the `craftcms` option was added in 1.21.2, but not present in 1.21, 1.21.1, so there could still be issues here, unless the exact schema is matched for each version as you've highlighted.

Maybe it is worth raising the possibility of the schema fetching being dynamic on the main ddev repository? It likely needs to have some form of joined up process to work reliably across the main code and this plugin, or even some form of internal ddev command like `ddev schema` to return valid values?

**Comment by nico-loeber** [comment]
Changing configuration options on a patchlevel is not a good habbit, but well... In this case storing the schemata in the plugin doesn't make any sense at all, as I can not release a new version of the plugin for every ddev patchlevel release.

I already developed a schema provider that can download the schema from a github release.
Means if you are using ddev in version 1.21.1 it will download the file at a given path from that github release.
There is no caching yet so this requires an internet connection to work properly on every startup of the IDE.

So the todo would be:
- Add configuration schema to the ddev repository
- Use RemoteSchemaFactory instead of the local one
- Implement Caching
- Provide fallback (Network error handling)

It would be very helpful if you @jamesmacwhite  could add the schema to the main ddev repository. 
I had a talk about this with @rfay in the past but we didn't finally decide whether this is a good idea. As soon as the schema is placed in the repo it has to be maintained on every configuration change.

**Comment by jamesmacwhite** [comment]
I think it certainly highlights static schema can't work in this, adding configuration options within incremental releases I guess isn't ideal, but I guess the argument is keep up to date on major PHP projects and having a project value not added until the next major version i.e. 1.22, would delay things.

It sounds like you've implemented a lot of background work to make it more dynamic, we just need to agree an implementation into the DDEV repository.

I can add a feature request linking to this to reopen the discussion on it and go from there?

**Comment by rfay** [comment]
It actually looks to me like this has nothing whatever to do with the plugin, am I right? This is about PhpStorm validating the config.yaml? The normal way to handle PhpStorm validating the config.yaml would be 
* drud/ddev#4511

And the plugin shouldn't be involved at all?

**Comment by jamesmacwhite** [comment]
It is related to the plugin because currently it bundles a DDEV schema for 1.19 which is used to validate the config.yaml. That currently is triggering false errors for someone who happens to be running say DDEV 1.21.4, because it's using a specification of 1.19, so for the example case, I'm using the project type value of `craftcms`, the static 1.19 schema doesn't have this option present (because in 1.19, it doesn't exist of course) and therefore flags in the IDE that this project value is invalid, that is because it's not listed here:

https://github.com/php-perfect/ddev-intellij-plugin/blob/main/src/main/resources/schema/ddev-config-1.19.schema.json#L31-L50

So while this was correct for 1.19, it isn't for 1.21.4

Of course DDEV itself will happy carry on and provision such environment because it knows that project value is valid with the version being used.

Based on the conversations, the issues as I understand it are:

1. The DDEV schema being static means it has become outdated and therefore now no longer includes newer options. This could now make PHPStorm show false errors with the config.yaml when they aren't in fact errors.
2. @nico-loeber has highlighted that having the schema in the plugin itself is a potential issue given any schema change would require a plugin update to be made. Therefore the conversation to change this and make it more dynamic and ideally sitting in the main DDEV repository is the main discussion area.
3. One way or another the schema needs to be maintained across releases, but having it within the main DDEV project is likely the best solution, as then it could be distributed to multiple places.

However, if we went with the Schema Store option, the plugin might not need to directly reference it, if PHPStorm is automatically capable of pulling in schemas from sources, but we'd still need to move some form of schema definition into the main project I would have thought?

**Comment by rfay** [comment]
Right, the schema shouldn't need to be added by the plugin in the first place, and I'm not sure how it ever related to the (enormous) value the plugin adds. We should follow this up by getting and maintaining a standard schema as in the other issue.

**Comment by jamesmacwhite** [comment]
Yes. I think @nico-loeber originally bundled a schema file with the plugin as a temporary solution, but acknowledging that it is not the best way to handle it. Based on the above, it sounds like you may have both had a conversation around this previously, so it's now come back full circle since I've raised it and now we will look at implementing it in a way that's more maintained and manageable going forward, so this plugin can benefit along with any others potentially.

**Comment by nico-loeber** [comment]
I think adding the schema to a store doesn't solve this issue.
PHPStorm would need to know which version of ddev you are using to match the schema I think.
Please tell me if I am wrong.
Thats why my idea was from the beginning to let the plugin load the correct version of the schema and if there is none available provide a fallback.
The fallback is 1.19 as it was the most current at this point of time.
Due to the fact that I wanted to get the plugin relesased I decided to publish it with the fallback schema only.
But you can find a RemoteSchemaFactory in the git history that will try to load the the schema for a given ddev version number from the ddev github repository. Of course this can be changed to a schema store if the schema is available there for each ddev version.

Anyway, the first step would be to provide a schema in the ddev repository.
I am not sure if it is a good idea to automatically generate it, as the schema will probably contain more information, than the the go code has (Valid Values, Examples and so on).

**Comment by rfay** [comment]
I think all of these tools use the "latest" schema, and IMO that's fine. For example, if I edit a goreleaser yaml file, or (I think) a mkdocs-material file, it just automatically validates and warns. They must all just be using latest, IMO that's perfect.

**Comment by nico-loeber** [comment]
I don't think that would be the perfect solution to just provide the latest schema as phpstorm might suggest you configuration options that are invalid in your ddev version.
Common configurations like Open API oder even docker compose use versioning for their configurations. So there is a schema for each version of the configuration.
But... for me it would be okay to just provide the latest available schema. I would just like to point out that we could do better...

**Comment by nico-loeber** [comment]
For now I have just added `craftcms` as an valid option for the configuration schema in the plugin.
I would still suggest placing the schema somewhere else than in the code base of the plugin, this was just an interim solution.

**Comment by nico-loeber** [comment]
@rfay, is there a way we can place the ddev config schema in the ddev repository?
For ddev 1.22 I guess the config parameters `host_phpmyadmin_port`, `phpmyadmin_https_port` and `phpmyadmin_port` are removed from the `config.yaml`. Also the schema of the plugin does not allow php `8.2` as a valid value yet.

It would be great if there is a release workflow that releases a new schema for each new ddev version and the plugin is just downloading it from somewhere.
I already implemented a prototyp that is downloading the schema from a github repository based on a release with the same number as the version number of the installed ddev binary. In that way the validation is always in sync with the ddev version you have currently installed.
I'm also open for other ideas.

**Comment by rfay** [comment]
I really want to do it (or hoped that @jamesmacwhite would do it, but never heard from them again. )

* https://github.com/ddev/ddev/issues/4511

**Comment by jamesmacwhite** [comment]
@nico-loeber @rfay Hi both, sorry I didn't get around to looking at this in the end, given it's not that much of an issue, but the soluition I think discussed on the DDEV repository was to submit a schema through: https://www.schemastore.org/json/. If that's still something we propose to resolve the issue, then I can look at creating it.
