### ISSUE TITLE
Automatically set up Node.js interpreter for ddev projects

### ISSUE THREAD

**Issue by nico-loeber** [php-perfect/ddev-intellij-plugin#156]
### Discussed in https://github.com/php-perfect/ddev-intellij-plugin/discussions/155

<div type='discussions-op-text'>

<sup>Originally posted by **mikesnoeren** February  6, 2023</sup>
It would be great if interpreters like Node.js automatically get set-up so we have tighter integration between PhpStorm and DDEV. Currently I still have to set this up manually (or, maybe I am doing something wrong?)</div>

**Comment by nico-loeber** [comment]
Hey @mikesnoeren,

Since the coding assistance in phpstorm for remote node interpreters is not supported, implementing node integration for the plugin is only of limited use.

I will give it a try when I find some time anyway, but without priority, as it probably won't solve your problem.

---

Elena Pogorelova commented 8 Feb 2023 13:40
these are known limitations when using remote interpreters:
Tailwind: [WEB-53172](https://youtrack.jetbrains.com/issue/WEB-53172/CSS-class-auto-completion-for-Tailwind-does-not-work-when-using-a-remote-Node.js-interpreter-Docker-ssh)
Node.js coding assistance: [WEB-54178](https://youtrack.jetbrains.com/issue/WEB-54178/Allow-enabling-Node.js-coding-assistance-when-using-remote-Node.js-interpreter)
Version: [WEB-52959](https://youtrack.jetbrains.com/issue/WEB-52959/Show-version-of-Node.js-interpreter-in-Preferences-Languages-Frameworks-Node.js-and-NPM-if-its-remote)

---

https://youtrack.jetbrains.com/issue/WEB-53172/CSS-class-auto-completion-for-Tailwind-does-not-work-when-using-a-remote-Node.js-interpreter-Docker-ssh

**Comment by mikesnoeren** [comment]
Hi @nico-loeber,

Yes, I've been doing some investigation and it doesn't seem possible at the moment, however, I believe they are working on fixing this? 

For now I just ended up installing Node.js locally, not ideal, but it gets the job done.
Thanks for taking your time with this, for me this is no longer a priority either.
