### ISSUE TITLE
"DDEV integration" not found in Marketplace

### ISSUE THREAD

**Issue by rfay** [php-perfect/ddev-intellij-plugin#16]
Following the instructions to install I went to plugins -> Marketplace to look for "DDEV' or "DDEV integration" but don't see it there.
<img width="934" alt="Cursor_and_Preferences" src="https://user-images.githubusercontent.com/112444/162393956-04f73693-52ec-46b7-9c41-914d082092f5.png">

**Comment by nico-loeber** [comment]
I have added details on testing non-stable versions in [CONTRIBUTING.md](https://github.com/php-perfect/ddev-intellij-plugin/blob/main/CONTRIBUTING.md#testing-of-pre-releases). I also linked the plugin in the Jetbrains Market Place in the [README.md](https://github.com/php-perfect/ddev-intellij-plugin/blob/main/README.md#installation), where you can also download non-stable versions manually.

I think that should be enough for now.

Please let me know if you have any problems installing the plugin.

**Comment by nico-loeber** [comment]
Closing this as the alpha testers had no more issues installing the plugin.
