### ISSUE TITLE
Incompatible with PHPStorm 2023.1

### ISSUE THREAD

**Issue by Firesphere** [php-perfect/ddev-intellij-plugin#170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you sure that this bug is related to this DDEV Integration Plugin?

- [X] I am sure

### Describe the bug

```
Plugin 'DDEV Integration' (version '1.0.4') is not compatible with the current version of the IDE, because it requires build 223.* or older but the current build is PS-231.8109.199
```
System details:

PhpStorm 2023.1
Build #PS-231.8109.199, built on March 30, 2023
Runtime version: 17.0.6+10-b829.5 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.15.0-69-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 1964M
Cores: 8
Registry:
    debugger.new.tool.window.layout=true
    run.processes.with.pty=TRUE
    ide.experimental.ui=true

Non-Bundled Plugins:
    some.awesome (1.14)
    PHPUnit code coverage (0.5.0)
    com.dimabdc.idea.php.phpunit (0.5.1)
    com.kalessil.phpStorm.phpInspectionsEA (4.0.7.1)
    ru.adelf.idea.dotenv (2023.1)
    de.espend.idea.php.toolbox (6.2.0)
    de.espend.idea.php.annotation (9.2.0)
    izhangzhihao.rainbow.brackets (2023.2.6)
    zielu.gittoolbox (500.0.5+213)
    mobi.hsz.idea.gitignore (4.4.4)

Current Desktop: KDE

### Steps to reproduce

Upgrade PHPStorm to the latest 2023 version

**Comment by nico-loeber** [comment]
I'm aware of this, will be fixed within the next few days.
It's a bit complicated to prepare plugins for the next versions, at least I don't know how I can publish a new compatbilt version of the plugin before the next stable version of phpstorm is released.

**Comment by nico-loeber** [comment]
Small update: Sadly there are changes to the status bar widget implementation.
I need to find a way to work with the RC releases better to solve such issues before the stable release of PHPStorm... :-/

**Comment by rfay** [comment]
Just chiming in: We know how hard it is to maintain something like this, and we sure appreciate your contribution to the community by doing it!

**Comment by aksld** [comment]
Don't hesitate to tell us if you need help to test !

**Comment by nico-loeber** [comment]
Version 1.0.5 supporting IntelliJ Platform 2023.1 is released and awaiting review in the JetBrains marketplace.

In the meantime you can install the plugin from zip attached to the release:
https://github.com/php-perfect/ddev-intellij-plugin/releases/tag/1.0.5

I had to define the thread the ddev actions are executed in for each action as well as some changes to the implementation of the integrated DDEV Terminal and the status bar. Please let me know if you experience any issues.

> Just chiming in: We know how hard it is to maintain something like this, and we sure appreciate your contribution to the community by doing it!

Thank you @rfay, but I was not well prepared for the release of PHPStorm 2023.1 there is no excuse.

In case someone knows a good workflow for compiling plugins with RC versions on a test branch or something like that, please let me know. Maintaining a development branch adds too much overhead for me with my current workflows.

**Comment by nico-loeber** [comment]
The new release was approved by JetBrains and is now available for installation via the jetBrains Marketplace.

**Comment by shochdoerfer** [comment]
Working fine! Thanks!
