### ISSUE TITLE
DDEV v1.22.0 removes PHPMyAdmin from core

### ISSUE THREAD

**Issue by rfay** [php-perfect/ddev-intellij-plugin#207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you sure that this bug is related to this DDEV Integration Plugin?

- [X] I am sure

### Describe the bug

Thanks so much for maintaining this!

I just wanted to make sure you knew that the `phpmyadmin` feature, `ddev launch -p`, etc has been removed from DDEV core in v1.22.0, which will be out shortly. 

Since this plugin has excellent integration with the PhpStorm database browser, maybe it should just offer that?

**Comment by nico-loeber** [comment]
Hey @rfay,
There are some lines of dedicated code for the phpmyadmin configuration in the plugin right now. 
I guess they need to be removed. If there is any additional (service) container (adminer, phpmyadmin, ...) offering a web url, it should automatically appear in the quick access menu.

Thanks for the information, I will carefully check this.

**Comment by nico-loeber** [comment]
The plugin works well with DDEV v1.22.0 as the dba service is handled optional.
I will keep this open as a reminder to remove the dba specific code for the next release.

Is the same planned for the mailhog service @rfay? This also a standalone web service that is currently bundled in the web container...
