### ISSUE TITLE
Mailpit Support

### ISSUE THREAD

**Issue by blankse** [php-perfect/ddev-intellij-plugin#232]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you sure that this bug is related to this DDEV Integration Plugin?

- [ ] I am sure

### Describe the bug

After update to ddev >v1.22.2 it is not possible to open Mailpit with the action menu:
![image](https://github.com/php-perfect/ddev-intellij-plugin/assets/998558/36fd2b5b-6c82-47fa-8f0b-12482e64744f)
Only "Open Website" is available. 

Can you add Mailpit to the action menu like Mailhog in ddev <v1.22.2?

Thanks for creating this plugin. It helps us a lot 👍🏼

**Comment by nico-loeber** [comment]
Hi @blankse,

The URL to Mailpit has to be exposed in `ddev describe --json` to be available in the status bar.
I will check if this possible.

**Comment by nico-loeber** [comment]
@rfay that was fast... Thanks! :D

Will be added for the next release.

**Comment by nico-loeber** [comment]
Support is now available on the main branch.
There will soon be a new release of the plugin (as soon as there is a new Intellij major release).
