### ISSUE TITLE
DataSource auto configuration not working on Manjaro Linux

### ISSUE THREAD

**Issue by nico-loeber** [php-perfect/ddev-intellij-plugin#24]
> Tested on my Laptop (Manjaro Linux)
> 
> heavy_check_mark Run DDEV actions via GUI heavy_check_markQuick access DDEV Services heavy_check_markAuto configure PHP Remote Interpreter x Auto configure data source heavy_check_mark Assistance and completion for DDEV configuration file question DDEV version check (where can I test it?) heavy_check_mark Integrated DDEV terminal
> 
> ![image](https://user-images.githubusercontent.com/211294/163943758-00f4ca27-fa46-4a1a-813d-a9dfe81e0fcd.png)

The port of the integration was detected. Found that I have to replace "localhost" with "127.0.0.1" to get it run.

jdbc:mysql://localhost:49171/db?user=db&password=db

vs. 

jdbc:mysql://127.0.0.1:49171/db?user=db&password=db

_Originally posted by @cmuench in https://github.com/php-perfect/ddev-intellij-plugin/discussions/21#discussioncomment-2590625_

**Comment by nico-loeber** [comment]
Thanks for reporting @cmuench! So the problem was only that localhost was not resolved correctly?
I think this shouldn't be a problem with the plugin itself. Of course we could change the address to 127.0.0.1 but first i would like to know it this is indeed the better solution.
Please keep me updated on this!

**Comment by nico-loeber** [comment]
Is it possible, that the ddev database was not running yet?

**Comment by cmuench** [comment]
Problem is only related to the resolution of "localhost". I will try that in a Arch Linux.

**Comment by cmuench** [comment]
@nico-loeber Containers are running. For me it's not an issue of the plugin, but maybe it's good to have a troubleshoot page. In my cast it's a standard Manjaro configuration.

**Comment by cmuench** [comment]
@nico-loeber On my Arch Linux it works fine.
Fun fact... localhost does resolve to the same IPv6 ip address.

**Comment by nico-loeber** [comment]
Okay, I would like to reduce documentation to a minmum, as the goal of this plugin is to simplyfy the use of ddev in your everyday work. So additional documentation should be avoided whenever possible.

I will concider using 127.0.0.1 instead of localhost.
Referencing your machine by localhost looked to me like the best solution as it is IPv4 and IPv6 compatible.

Still I'm not sure if this is not a general issue of your system as localhost should always refernce your own system as 127.0.0.1 and ::1. Docker should listen on those interfaces I think.
Maybe you can check in detail what the issue is. 
Which IP protocol is used (v4/v6), does it refer to your own system? Is docker bound to this interface?

**Comment by cmuench** [comment]
> Okay, I would like to reduce documentation to a minmum, as the goal of this plugin is to simplyfy the use of ddev in your everyday work. So additional documentation should be avoided whenever possible.
> 
> I will concider using 127.0.0.1 instead of localhost. Referencing your machine by localhost looked to me like the best solution as it is IPv4 and IPv6 compatible.
> 
> Still I'm not sure if this is not a general issue of your system as localhost should always refernce your own system as 127.0.0.1 and ::1. Docker should listen on both those interfaces I think. Maybe you can check in detail what the issue is. Which IP protocol is used (v4/v6), does it refer to your own system? Is docker bound to this interface?

Right. Will check that. On my Arch it works with localhost. On Manjaro it's not working. Need to compare both setups.

**Comment by cmuench** [comment]
> > Okay, I would like to reduce documentation to a minmum, as the goal of this plugin is to simplyfy the use of ddev in your everyday work. So additional documentation should be avoided whenever possible.
> > I will concider using 127.0.0.1 instead of localhost. Referencing your machine by localhost looked to me like the best solution as it is IPv4 and IPv6 compatible.
> > Still I'm not sure if this is not a general issue of your system as localhost should always refernce your own system as 127.0.0.1 and ::1. Docker should listen on both those interfaces I think. Maybe you can check in detail what the issue is. Which IP protocol is used (v4/v6), does it refer to your own system? Is docker bound to this interface?
> 
> Right. Will check that. On my Arch it works with localhost. On Manjaro it's not working. Need to compare both setups.

Would be better if it works with "localhost",  because it's also the information we see in "ddev describe".

**Comment by nico-loeber** [comment]
Hey @cmuench, are there any news on this?
Is there anything we can do in the plugin to solve this issue?
As you mentioned you would not support the idea to change the host to 127.0.0.1.

**Comment by cmuench** [comment]
> Hey @cmuench, are there any news on this? Is there anything we can do in the plugin to solve this issue? As you mentioned you would not support the idea to change the host to 127.0.0.1.

It works on my MacBook and Arch with localhost.
I guess it's some special network thing on Manjaro.
If I have free time, then I will try to install a fresh Manjaro in a VM to test.
IMHO we can close the issue and reopen it, if needed.

**Comment by nico-loeber** [comment]
Okay thanks @cmuench. Keep me updated if I can do anything on my side to solve this issue.

**Comment by SpraxDev** [comment]
I think I was able to reproduce this issue. PHPStorm is configured to `localhost` while docker is exposing the port on `127.0.0.1`. But pinging localhost resolves to the IPv6 interface.
Setting the data source to `127.0.0.1` instead of `localhost` resolves the issue

![ping localhost](https://user-images.githubusercontent.com/7331598/167259146-db899271-49aa-426f-8f66-9913b41c2e14.png)
![docker ps](https://user-images.githubusercontent.com/7331598/167259097-40364d2b-390b-49f9-86bd-440489241fbb.png)

**Comment by nico-loeber** [comment]
This seems to be an issue with ddev not supporting IPv6.
https://github.com/drud/ddev/issues/3817

@rfay suggests using 127.0.0.1 to bypass this issue, so I will change this in the data source configuration.

**Comment by nico-loeber** [comment]
127.0.0.1 will be used from now on. I will probably publish an alpha3 version today.
Feedback is welcome!
