### ISSUE TITLE
Let JSON Schema Store to do the config validation

### ISSUE THREAD

**Issue by stasadev** [php-perfect/ddev-intellij-plugin#256]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you sure that this bug is related to this DDEV Integration Plugin?

- [X] I am sure

### Describe the bug

From [Discord](https://discord.com/channels/664580571770388500/1172475039766036500/1172475039766036500):

![image](https://github.com/php-perfect/ddev-intellij-plugin/assets/24270994/1d19ecf3-d455-484d-83d0-c044c4f3e5a6)

Following up the discussion

- https://github.com/php-perfect/ddev-intellij-plugin/issues/141

This plugin should let the Schema Store JSON to do the validation:

- https://github.com/ddev/ddev/pull/5281#issuecomment-1688971679 didn't happen
- https://github.com/SchemaStore/schemastore/pull/3158

**Comment by nico-loeber** [comment]
Will be done for the next release.

If someone likes to pull request it:
* Remove the schema factory:
https://github.com/php-perfect/ddev-intellij-plugin/blob/main/src/main/java/de/php_perfect/intellij/ddev/config/ConfigJsonSchemaProviderFactory.java
* Remove the Schema file (referenced in the factory)
* Remove references to the Schema factory, like in the plugin.xml
* Maybe there are also tests to remove

**Comment by mandrasch** [comment]
Nice, thanks very much! 👏
