### ISSUE TITLE
Feature request: GUI ddev actions

### ISSUE THREAD

**Issue by calien666** [php-perfect/ddev-intellij-plugin#26]
Referring to https://github.com/php-perfect/ddev-intellij-plugin/discussions/21#discussioncomment-2591500 I would prefer the Actions take place in the footer section, where the ddev status is shown. In this case it would be more effective to use these actions fast.

**Comment by nico-loeber** [comment]
DDEV is concidered as a development tool, same as vagrant for example. These are located in the tools action group. I think they make sense where they are.
