### ISSUE TITLE
Version 1.1.1 is not compatible with PhpStorm 2023.3 Build #PS-233.11799.232

### ISSUE THREAD

**Issue by kenrbnsn** [php-perfect/ddev-intellij-plugin#268]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you sure that this bug is related to this DDEV Integration Plugin?

- [X] I am sure

### Describe the bug

Can't start the plugin

### Steps to reproduce

1) Start PhpStorm with the plugin enabled.
2) Get a message that the plugin is not compatible with the version of PhpStorm

**Comment by iamntz** [comment]
@kenrbnsn as a temporary fix, you can:

1. download the last release
2. unzip it
3. unzip `lib/instrumented-ddev-intellij-plugin-1.1.1.jar` (.jar files are just zip with a different extension)
4. edit `lib/instrumented-ddev-intellij-plugin-1.1.1.jar/META-INF/plugin.xml`
5. search for `<idea-version since-build="232.8660" until-build="232.*`
6. replace `until-build="232.*` to a greater version (233)
7. zip everything back as it was
8. in Storm go to plugins => install from disk
9. select the updated zip file
10. restart IDE
11. continue coding awesome stuff

<img width="785" alt="image" src="https://github.com/php-perfect/ddev-intellij-plugin/assets/132062/da045ca3-3c7f-4973-a3b8-b2b67ffc0587">

**Comment by nico-loeber** [comment]
Hey @kenrbnsn,
This pull request (https://github.com/php-perfect/ddev-intellij-plugin/pull/270) is already compatible with the 233 release, but there is some issue with the build pipeline (Plugin verifier) why it is not yet released.

@iamntz, I would  not suggest you to "fake" the compatibility settings, as this version of the plugin is not compatible with the latest Intellij Releases.
But you can download the compatible version directly from the build pipeline: https://github.com/php-perfect/ddev-intellij-plugin/actions/runs/7130828338
Thanks for explaining how to install the plugin from zip!

**Comment by kamilmaliszewski** [comment]
Hey @nico-loeber , I can't install it from zip. I have a strange error. After choose `instal Plugin from disk` and choose `ddev-intellij-plugin.zip` from your link. 

![image](https://github.com/php-perfect/ddev-intellij-plugin/assets/26593996/6b9e1a45-9e65-4214-9225-99adf45e8ebd)

**Comment by webworka** [comment]
@kamilmaliszewski You have to unpack the zip und install the zip that is inside of the package.

**Comment by graham73may** [comment]
I've never had to do this before, can I just check... Now that I've installed from the .zip/.jar file, will it still recognise when a new update is released? 

Or do I need to keep an eye on things and basically re-add the Marketplace version of this plugin?

**Comment by nico-loeber** [comment]
It should automatically update as the version published is higher than the one from the build pipeline (0.0.1-dev), but I never tried it myself yet, @graham73may.

Hope to publish it soon, but sadly I didn't get any feedback on this blocking issue yet: https://github.com/JetBrains/gradle-intellij-plugin/issues/1505
I don't want to publish the new version of the plugin without it passing the plugin verifier task, that checks compatibility with different IDE variants and versions.

**Comment by saidatom** [comment]
@nico-loeber something is wrong with that version i can't select any action.
![Screenshot 2023-12-13 at 19 19 52](https://github.com/php-perfect/ddev-intellij-plugin/assets/2377368/dd7db7f1-6927-4548-8727-554d43587bd2)

**Comment by aksld** [comment]
Hi there,

Do you have any news?
I've noticed that JetBrains isn't moving much.
Isn't that strange? Are you the only plugin to have this problem?

What can we do to help?

**Comment by iamntz** [comment]
> Are you the only plugin to have this problem?

Surely it is not. 

Editorconfig & CSV are ones that constantly are (or at least used to be) behind with EAP. But I don't remember if they ever were left behind with the stable version.

I'd say the right aproach would be to test it on EAP rather on stable?

**Comment by nico-loeber** [comment]
@iamntz You can test your plugins on EAP but it is not that easy.
JetBrains offers you a lot of build tools to release your plugin but they are quite hard to configure for everything else than the "normal" release cycle based on the current or a previous IntelliJ (PHPStorm) release.
Your plugin.xml gets automatically patched for compatible versions, your plugin is automatically tested against current versions for copatibility and so on.
If you build your plugin with an EAP release it might not be compatible to the current releases and the pipeline will fail.
Of course you can just skip that step but then you will loose compatibility information to other product release and manual testing is... not nice.

I am quite sure the branch mentioned above is compatible to current versions but I don't want to skip all the verification steps when publishing it. I hoped for faster feedback / support from JetBrains on the mentioned issue...

**Comment by MattWilcox** [comment]
Not a useful comment here (other than to say, yep - also having this issue) - but do want to drop a thanks for looking into it Nico, and the work on the plugin. Appreciate it.

**Comment by graham73may** [comment]
@nico-loeber 

I was having some issues with the plugin being installed from disk but not really working. I noticed [your instructions](https://github.com/php-perfect/ddev-intellij-plugin/issues/268#issuecomment-1847102402) had been updated so was giving them a go. I get all the way to the end and get this error: 

<img width="350" alt="image" src="https://github.com/php-perfect/ddev-intellij-plugin/assets/6642498/ff9b117b-0e57-4171-8624-353633e674f6">


I'm not sure what I'm doing wrong, any ideas? 

When I re-zip the edited .jar's extracted files with Archive Utility it's much bigger. I'm literally compressing the folder, it gets called .zip, I then rename it to .jar. (Assuming maybe this is not the correct process?)

**Comment by nico-loeber** [comment]
You shouldn't edit any of the files @graham73may, use one of the versions from the build pipeline of the pull request, as mentioned above.
Editing files in a signed version of the plugin should even avoid it to be loaded, or at least trigger a warning as the signature does no longer match.

I will try to release the current version of the plugin this weekend without the compatibility check...
I hoped for some support from JetBrains so I don't need to bypass the compatibility checks in the release workflow but they all seem to be on holidays since the release of 2023.3.

**Comment by graham73may** [comment]
Only just noticed that the steps RE editing the .xml file were not actually from you! 
Sorry to bother you Nico!

The .zip from the build pipeline is working :)

**Comment by nico-loeber** [comment]
You're welcome!
Sorry for the inconvenience with the plugin.

**Comment by nico-loeber** [comment]
I just published a new release that should be compatible, even if the validation task fails, due to the problem in the pipeline.
Please let me know if you encounter any issues.

**Comment by grempa** [comment]
Works for me and updated from the workaround solution without hesitation. Thanks for your work! 👍

**Comment by prometheus76** [comment]
Works for me. Thank you for version 1.2.0

**Comment by webworka** [comment]
Works for me too. Thank you!

**Comment by Skullsneeze** [comment]
@nico-loeber I think this could be closed. Just updated through the UI of PHPStorm (Version 1.0.4 -> 1.2.0) and updated without any issues!

**Comment by nico-loeber** [comment]
Thanks for your feedback @Skullsneeze!
Closing this now. Glad it works well for everyone, after the difficulties we had...
