### ISSUE TITLE
Feature request: GUI ddev own written actions

### ISSUE THREAD

**Issue by calien666** [php-perfect/ddev-intellij-plugin#27]
Having own actions/commands, as in .ddev/commands/web even in the actions menu integrated would be a nice feature, as there are some actions, some will have default in his projects but more in use as the default start/stop/configure.
Thinking about, if there would be some ddev config added as comment, if this script is standalone or needs a terminal, to avoid using terminal scripts as actions.

**Comment by nico-loeber** [comment]
I think this is a already covered by #14. 
We plan to provide run configurations for custom ddev commands in .ddev/commands/web and maybe also for other containers.
Sadly this feature is not in the scope for version 1.0, as we prioritized getting the current features stable.

**Comment by calien666** [comment]
I'm sorry, I didn't see the other issue. But getting this in a future version would be great. Thanks for your great work
