### ISSUE TITLE
DDEV Integration entered unknown state

### ISSUE THREAD

**Issue by kdborg** [php-perfect/ddev-intellij-plugin#299]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you sure that this bug is related to this DDEV Integration Plugin?

- [X] I am sure

### Describe the bug

After having PHPStorm minimized for some time, I reopened the window and the error message popped up.

Clicking on "Sync DDEV State" did not fix the issue.

### Steps to reproduce

1. Minimize PHPStorm with a project using DDev.
2. After a while, reopen the project.
3. View error.

**Comment by rfay** [comment]
Did you review open issues and look for solutions there before opening this?

https://github.com/php-perfect/ddev-intellij-plugin/issues?q=is%3Aissue+is%3Aopen+%22unknown+state%22

**Comment by nico-loeber** [comment]
@kdborg, this is a known issue that can have various causes, its hard to find one solution for this.
Please see the issue @rfay has linked.

Closed as duplicate.
