### ISSUE TITLE
Broken due to path in Nix

### ISSUE THREAD

**Issue by freelock** [php-perfect/ddev-intellij-plugin#301]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you sure that this bug is related to this DDEV Integration Plugin?

- [X] I am sure

### Describe the bug

```
de.php_perfect.intellij.ddev.cmd.CommandFailedException: Failed to execute /usr/bin/ddev --version --json-output
	at de.php_perfect.intellij.ddev.cmd.DdevImpl.executePlain(DdevImpl.java:57)
```

ddev binary gets installed at /run/current-systems/sw/bin/ddev in NixOS.

I think you can use `/usr/bin/env ddev` to reliably get the ddev location -- this is how to fix shell shebang lines for Nixos, and when I execute that I get ddev's normal output...

### Steps to reproduce

1. Install NixOS
2. Install PHPStorm as a NixOS package
3. Install DDev plugin

You get the error that starts with the message above, and no ddev integration.

**Comment by stasadev** [comment]
A temporary fix (I don't know if anything is planned for `/usr/bin/env ddev`) is to set a custom path in Preferences > Tools > DDEV Integration > Path to your ddev binary.

**Comment by freelock** [comment]
I tried setting this to /run/current-system/sw/bin/ddev (which is the output of `which ddev`) but I'm getting Invalid DDEV Binary: No version information could be retrieved from /run/current-system/sw/bin/ddev.

**Comment by rfay** [comment]
Well, if you have ddev properly installed, then `/run/current-system/sw/bin/ddev --version` should get you some output. It sounds like it's not actually installed correctly? What is the output of this command? 
```
which ddev && ls -l $(which ddev) && /run/current-system/sw/bin/ddev --version
```

**Comment by nico-loeber** [comment]
As @stasadev already wrote, you can set the path to the ddev binary in the editor settings. The path you see there is autodetected by the plugin that will search for ddev installed in common paths or if `ddev` is in your PATH variable.
As soon as a ddev binary is found the plugin will no longer search for one automatically.
When changing the path in the settings the plugin will try to verify that the path entered is valid. If there is no ddev like version output you get this error.
Please double check your path and let me know if I can assist you any further @freelock.

**Comment by nico-loeber** [comment]
I will close this issue due to inactivity. If you need further support you can find me on the DDEV discord server or you can write me an email. I am quite sure this is a specific issue with your configuration and not with the plugin itself.

**Comment by freelock** [comment]
Sorry, traveling this week, on spring break/eclipse trip.

Here's the output of Randy's request:

```
❯ which ddev && ls -l (which ddev) && /run/current-system/sw/bin/ddev --version
/run/current-system/sw/bin/ddev
lrwxrwxrwx 1 root root 64 Dec 31  1969 /run/current-system/sw/bin/ddev -> /nix/store/yzbg4jhj69qgir4f0xy1xzszrpwash2k-ddev-1.22.7/bin/ddev
ddev version 1.22.7
```
(fish shell so dropped the $ on $())

I did set the ddev path in the preferences, but I still get errors...

**Comment by freelock** [comment]
![image](https://github.com/php-perfect/ddev-intellij-plugin/assets/46937/359af3a8-a805-4fd8-a3de-1f156495863d)

When setting the ddev path in File -> Settings -> Tools -> DDev integration, that's the message I get when I press Apply or OK, and it won't save.

**Comment by freelock** [comment]
It also doesn't apply if I use the symlink path - /nix/store/yzbg4jhj69qgir4f0xy1xzszrpwash2k-ddev-1.22.7/bin/ddev (which would change every time DDev gets updated).

```
❯ /nix/store/yzbg4jhj69qgir4f0xy1xzszrpwash2k-ddev-1.22.7/bin/ddev --version
ddev version 1.22.7
```

**Comment by freelock** [comment]
```
❯ file /nix/store/yzbg4jhj69qgir4f0xy1xzszrpwash2k-ddev-1.22.7/bin/ddev
/nix/store/yzbg4jhj69qgir4f0xy1xzszrpwash2k-ddev-1.22.7/bin/ddev: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /nix/store/1rm6sr6ixxzipv5358x0cmaw8rs84g2j-glibc-2.38-44/lib/ld-linux-x86-64.so.2, not stripped
```

**Comment by nico-loeber** [comment]
So `/nix/store/yzbg4jhj69qgir4f0xy1xzszrpwash2k-ddev-1.22.7/bin/ddev` as ddev path binary path in the settings works but will change over time? Did I understand that correctly?

**Comment by nico-loeber** [comment]
The reason for this issue seems to be the missing "v" prefix in the output of `ddev --version` that is currently expected by the regex. A possible fix is to make it optional in the regex that is parsing the output. It would also be interested to find out why it is missing... A pull request is welcome.

**Comment by freelock** [comment]
The current build recipe for DDev in nix has this section:
```
  version = "1.22.7";

  src = fetchFromGitHub {
    owner = "ddev";
    repo = "ddev";
    rev = "v${version}";
    hash = "sha256-bFQW12VzH+/OXTRBavEdfxnGowJt5TKM3r0UD64ALVs=";
  };

  vendorHash = null;

  ldflags = [
    "-extldflags -static"
    "-X github.com/ddev/ddev/pkg/versionconstants.DdevVersion=${version}"
    "-X github.com/ddev/ddev/pkg/versionconstants.SegmentKey=${version}"
  ];
  ```
  
  ... this is all passed to the Go compiler. I'm wondering if the Ddev version and SegmentKey flags should just have the "v" passed to them -- e.g. change the ${version} variable to include the "v" prefix -- I don't know nix well enough to know whether that version is expected to be just a semver or if that will work (I suspect it would). 

Maybe @rfay can comment on which would be preferred -- keep the version output consistent (if this will do it) or allow "v" to be optional in the version string?

**Comment by rfay** [comment]
This turns out to be a problem with the nix build, as we've talked about in Discord. I don't recommend changing this plugin, but instead doing a PR to the nix build to use a standard build technique.

**Comment by nico-loeber** [comment]
Closing this issue as it is probably a nix issue.

**Comment by montchr** [comment]
> I'm wondering if the Ddev version and SegmentKey flags should just have the "v" passed to them

@freelock You are correct!  By providing the `v` prefix to those flag values, the error in the plugin settings is resolved and the plugin can now recognize the `ddev` binary.

> e.g. change the ${version} variable to include the "v" prefix -- I don't know nix well enough to know whether that version is expected to be just a semver or if that will work (I suspect it would).

The `version` attribute must always start with a digit [[source](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#versioning)].

For that reason, the `v` prefix should probably be determined by the package expression's `src.rev` attribute.  `src.rev` is referring to the Git tag, which is the same value expected by those flags currently using `version`.

So here is what I would change in the snippet you posted:

```diff
  version = "1.22.7";

  src = fetchFromGitHub {
    owner = "ddev";
    repo = "ddev";
    rev = "v${version}";
    hash = "sha256-bFQW12VzH+/OXTRBavEdfxnGowJt5TKM3r0UD64ALVs=";
  };

  vendorHash = null;

  ldflags = [
    "-extldflags -static"
-    "-X github.com/ddev/ddev/pkg/versionconstants.DdevVersion=${version}"
-    "-X github.com/ddev/ddev/pkg/versionconstants.SegmentKey=${version}"
+    "-X github.com/ddev/ddev/pkg/versionconstants.DdevVersion=${src.rev}"
+    "-X github.com/ddev/ddev/pkg/versionconstants.SegmentKey=${src.rev}"
  ];
```

I will open a patch upstream.  Thanks for looking into this!
