### ISSUE TITLE
Changing the colima to Rancher Desktop causet the issue with ddev plugin in PHPStorm

### ISSUE THREAD

**Issue by Oleksii909** [php-perfect/ddev-intellij-plugin#304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you sure that this bug is related to this DDEV Integration Plugin?

- [X] I am sure

### Enter your error report ID (If available)

c0f0d9d00acd4f948b0c725e9bb504df

### Describe the bug

I had a working plugin using colima.
I installed Runcher Desktop and rebooted my PC.
I run the Runcher Desktop
I opened PhpStorm and the Ddev Plugin reported issue

**Comment by nico-loeber** [comment]
The output of `docker context show` could also be of interest... This is one thing that could have changed by installing Runcher I think.

**Comment by rfay** [comment]
`docker context ls` shows more, and pretty useful.

**Comment by nico-loeber** [comment]
> `docker context ls` shows more, and pretty useful.

Oh, thats nice! Didn't know that one yet!

**Comment by Oleksii909** [comment]
I was able to switch the docker context using `docker context use colima` and `docker context use rancher-desktop` and make ddev plugin to work for ddev project while both `colima` and `rancher desktop` were loaded.

**Comment by rfay** [comment]
You'll have to have the context set to the one you want in order to be able to use it. That's not something that the plugin can help you with.

**Comment by Oleksii909** [comment]
Now i have another question: Is it possible to point colima context to use another DOCKER ENDPOINT?
for example to use the ranchers endpoint `unix:///Users/oleksiibondarenko/.rd/docker.sock`

<img width="1050" alt="image" src="https://github.com/php-perfect/ddev-intellij-plugin/assets/73876066/81fb4742-3172-41fb-9b93-c3d0499eb243">

**Comment by rfay** [comment]
To change contexts, use `docker context use rancher-desktop` or `docker context use colima`

Contexts are actually symlinks, you can do lots of things with them.

But please ask unrelated questions in appropriate places and close this issue if you've got it sorted out. Support in https://ddev.readthedocs.io/en/stable/users/support/, we're happy to have you.
