### ISSUE TITLE
Change Plugin ID

### ISSUE THREAD

**Issue by nico-loeber** [php-perfect/ddev-intellij-plugin#311]
"intellij" is no longer allowed to be part of the plugin id. The current plugin id is "de.php_perfect.intellij.ddev". 
The plugin id is used many times in the plugin and all services ids are prefixed with this id. It has to be changed to something like "de.php_perfect.ddev_integration" and all packages and services need to be renamed.

This is requirment to publish a new version.

**Comment by Aneida** [comment]
I found this: https://intellij-support.jetbrains.com/hc/en-us/community/posts/13362061756050/comments/13368843442834

**Comment by mavolkmer** [comment]
reads to me like there is no need for changing plugin-id for an already published plugin - so this issue could be closed (?)

**Comment by nico-loeber** [comment]
Thanks for looking into this @Aneida!
I don't think we can close this issue, as it is still an issue that prevents creating a new release. The job does fail with this error.
Maybe we can just skip the validator for now, but this would only be a temporary fix.

**Comment by AkibaAT** [comment]
While the plugin verifier itself provides the `-mute TemplateWordInPluginId` to ignore the check, the pluginVerification Gradle config has no option for setting any mute flags.

**Comment by nico-loeber** [comment]
As already mentioned, the ID should not be changed, so I will close this issue.
