### ISSUE TITLE
Fix Plugin verifier task

### ISSUE THREAD

**Issue by nico-loeber** [php-perfect/ddev-intellij-plugin#312]
The plugin verifier tasks is an automated process to test the plugin for compatibility with different intellij products (IntelliJ Ultimate, Community, PHP and WebStorm, ...). This task is downloading current versions of these products and is testing if the plugin is installable and if there is use of deprecated api.
This task does currently fail because the disk space of the github runner is insufficient.
We need to find a solution for this. Can the disk size be increased? Can some other storage be mounted and used? Should we limit the products to only PHPStorm as it is the mostly used one?

**Comment by GBeushausen** [comment]
I would say as a quick fix we should limit to PHPStorm. The official DDEV docs also only specify PHPStorm.

**Comment by nico-loeber** [comment]
Maybe you want to pull request a fix @GBeushausen? The verifier tasks should be configurable with something like "supported versions" or "supported products" I think. 
This should be the place to look for its configuration options: https://github.com/JetBrains/intellij-plugin-verifier?tab=readme-ov-file#options
Please note: This is not that critical, because we can still release even if this task is failing on our pipeline but of course it should not as we want to make sure that whatever we release is compatible. ;)

**Comment by Cheoooon** [comment]
Add this in steps jobs seems to be going well.
```
      # Free GitHub Actions Environment Disk Space
      - name: Maximize Build Space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          large-packages: false
```

Check https://github.com/JetBrains/idea-gitignore/blob/8081b9ef732ea1b29d4d22b6fe83288f30a3a221/.github/workflows/build.yml#L180

Although https://github.com/php-perfect/ddev-intellij-plugin/issues/311 is still a problem...
```
Invalid plugin descriptor 'plugin.xml'. The plugin id should not contain the word 'intellij'.
```

https://youtrack.jetbrains.com/issue/MP-5911/Not-expected-plugin-verifier-warning-for-plugin-ID-containing-intellij

**Comment by nico-loeber** [comment]
Fixed by @Cheoooon, thank you!
