### ISSUE TITLE
Feature request: find the existing ddev path when editing a subdirectory

### ISSUE THREAD

**Issue by biati-digital** [php-perfect/ddev-intellij-plugin#35]
We usually create local projects with the following structure: /projects/project-name/app/public...

We run ddev config on /projects/project-name using --docroot=app/public so all the ddev configuration resides in the project-name directory.

In the public folder there's a lot of files from our CMS, we do not modify them in any way so we only open in PHP Storm the required subdirectory for example /projects/project-name/app/public/another-folder/my-working-dir so DDEV is not detected. 

If you select "Tools-> DDEV -> Configure" the command detects the current installation and displays the following error:

`It usually does not make sense to `ddev config` in a subdirectory of an existing project. Is it possible you wanted to `ddev config` in parent directory /projects/project-name`

Could it be possible to provide the path to the DDEV Installation? or even better just search if there's a current installation in a parent directory?

**Comment by nico-loeber** [comment]
Thanks for your feedback!

Opening just a sub-part of your project is not recommended for various reasons. PHPStorm / WebStorm will generate settings a .idea directory in its root directory, so everytime you open another sub part of your project your IDE will generate a new Project with new settings and caches can not be reused.
At least if I understood your workflow right.
Please note that  you also lack some features as the auto completion can't access your whole project, you won't have support for composer.json and package.json features as they are located in your project root und ddev is just one of these tools that gets initialized in the root of your project and your IDE needs to know it's configuration.

Apart of these facts it's an issue with ddev itself and not with the integration plugin, that it does not use the configuration in the parent directory. As you can see in the message, this configuration was already detected.

If you think this behavior should change, please open an issue in the ddev repository: https://github.com/drud/ddev/issues/new/choose
In case your feature request is implemented, some adjustments to this plugin may be necessary.

Still I would recommend you to always open your project on its root.

**Comment by biati-digital** [comment]
Hi @nico-loeber 

Thank's for your answer.

I'm afraid you did not get it right, we never open the project root with PHPStorm, it simply does not make sense for us as the root contains CMS files that will only make PHP Storm indexing slower and in general a mess as those files are always the same for multiple projects and we do not modify them so we do not need them in the editor. For autocompletition we use stubs, it's faster and easier.

We work in a subdirectory only, basically that subdirectory becomes our "project root" in PHP Storm, all the config resides there, like package.json, composer.json, git, etc. the .idea directory only exists on this subdirectory.

So just to clarify it a little more imagine the following structure:

`/projects/project-name/ `
here there's all the CMS files, a lot of files and folders we do not need to open with PHP Storm
here also you can find the .ddev directory

We only work with a directory inside the CMS for example:
`/projects/project-name/innerdir/myfolderthatweopenwithphpstorm`

A couple of months ago we created a tiny PHPStorm extension to do exactly this. It checks if the .ddev folder exists in the project root and if not it will check the parent directories to get the correct path when executing the `ddev` command

![CleanShot 2022-05-09 at 03 29 39](https://user-images.githubusercontent.com/1219228/167372713-a0e80f6a-ceb5-4e2b-91df-b0128eed3716.png)
 
I know it may not be ideal to only work in a subdirectpry but opening the entire project (including CMS) with PHP Storm it's really really slow.

Feel free to close this issue if you think this is not something that should be handled by the extension.

**Comment by nico-loeber** [comment]
Okay, thanks for clearing that up!

Configuring the working directory of ddev in the plugin settings would be possible but might have some unexpected consequences. Running ddev config will open the config.yml of ddev after doing so. If the configuration is out of your project this might become a problem. Also the compose file which is used for configuring the PHP Interpreter is found by the well known path .ddev/.ddev-docker-compose-full.yml relative to your project root.

If you provide a pull request that does not destroy any existing functionality when changing the working directory of ddev, that's fine with me.

I don't know which CMS System you are working with, but it looks to me like you are trying to workaround a bad architecture of your project. 
At my company I work with a CMS that we have maintained for about 20 years, and with many dependencies, and I have no problems opening a project at its source.

I will leave this open for now as I do not know how/if I can help you.
There is currently a ddev feature in development that allows you to start a project by name from any place. Maybe this can help you with this issue and can be supported by the plugin.

**Comment by biati-digital** [comment]
My situation it's more related to a limited device, PHPStorm alone sometime uses 6 to 8GB of ram, i also have running at the same time Docker, Sketch, Chrome, Fork, NPM tasks, etc. I'm just trying to find a way to make PHPStorm use less resources and excluding all the CMS files do help making the editor more responsive. 

I'll appreciate if you leave it open, i do believe this can be handled by the extension without issues but if a feature is already being developed in ddev it could hopefully make the implementation easier.

Thanks for your time and work.

**Comment by nico-loeber** [comment]
I have decided that this is out of the scope of the plugin for now, sorry.

If anyone else has a similar requirement, please comment here.
