### ISSUE TITLE
Set up NodeJS Remote Interpreter automatically

### ISSUE THREAD

**Issue by mikesnoeren** [php-perfect/ddev-intellij-plugin#353]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you sure that this bug is related to this DDEV Integration Plugin?

- [X] I am sure

### Describe the bug

After reading through an [issue](https://github.com/php-perfect/ddev-intellij-plugin/issues/156) I have opened a while ago, this should already work, but it currently doesn't, or am I misunderstanding how it should work? 

With PHPStorm now natively supporting coding assistance for remote node interpreters, it would be great if this could be looked into again. It would be ideal if opening a ddev project in phpstorm would automatically set up the Node.js remove interpreter like below:
![image](https://github.com/user-attachments/assets/165f4ff6-d853-4f36-a9fc-f1ef2da89396)

**Comment by nico-loeber** [comment]
The remote interpreter should be set correctly. I will take a look into this, thanks for reporting!

**Comment by AkibaAT** [comment]
One issue I see when trying it myself is that the plugin sets /usr/bin/node, which is incorrect. It should be /usr/local/bin/node to be explicit, or just node to use the PATH

The rest seems to be getting set up correctly.

**Comment by nico-loeber** [comment]
Looks like coding assistance is still not available for remote interpreters. But after merging @AkibaAT pr #358 the node and npm versions are detected correctly by the IDE. So everything looks fine to me.

![image](https://github.com/user-attachments/assets/c306809e-4de0-4573-b099-ead5d5b32695)
