### ISSUE TITLE
Incompatible with PhpStorm 2024.2.0.1

### ISSUE THREAD

**Issue by claudiu-cristea** [php-perfect/ddev-intellij-plugin#360]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you sure that this bug is related to this DDEV Integration Plugin?

- [X] I am sure

### Describe the bug

Just upgraded PhpStorm to 2024.2.0.1 and I'm getting

> Plugin 'DDEV Integration' (version '1.2.3') is not compatible with the current version of the IDE, because it requires build 241.* or older but the current build is PS-242.20224.427

### Steps to reproduce

Upgrade to PhPStorm 2024.2.0.1

**Comment by rfay** [comment]
Please search existing issues before creating new ones. The work on this has been done already, and the release will show up soon.
* https://github.com/php-perfect/ddev-intellij-plugin/issues/347
* https://github.com/php-perfect/ddev-intellij-plugin/issues/357
* https://github.com/php-perfect/ddev-intellij-plugin/pull/350

**Comment by claudiu-cristea** [comment]
I see a 1.2.4 release 2 days ago but JetBrains plugin page reports 1.2.3, so the IDE is not picking up 1.2.4

**Comment by rfay** [comment]
It takes some time for JetBrains to provide it/approve it/etc.

**Comment by claudiu-cristea** [comment]
OK, I've installed from zip and it works. Thank you, and sorry I've missed the other tickets
