### ISSUE TITLE
Add Error Reporting

### ISSUE THREAD

**Issue by nico-loeber** [php-perfect/ddev-intellij-plugin#37]
If a fatal error occurs which is related to a plugin IntelliJ allows you as a plugin developer to let people send you the error report.
To use this feature we need to
- [X] implement a backend to receive error reports ~(Elastic Search?)~ (sentry.io)
- [X] implement a ErrorReportSubmitter at the extension point errorHandler 

This seems to be a nice documentation on how to do it:
https://www.plugin-dev.com/intellij/general/error-reporting/

**Comment by SpraxDev** [comment]
I've implemented an ErrorReporter using the Sentry.io SDK and tested it but the change to the GitHub Action is untested (but *should* be fine).

@nico-loeber, you might want to additionally overwrite `SentryErrorReporter#getPrivacyNoticeText` and change the current return value of `SentryErrorReporter#getReportActionText`.
Oh and probably not leave my call to `Messages#showInfoMessage` it's kinda ugly (but worked for testing ^^)

- - -

little quote from c69dcba0c1d581530a79730936cac422e3602ddd:
> Information that is collected and sent to Sentry.io:
> * Full StackTrace
> * Plugin version
> * IDE Name and Version (including exact build *number*)
> * OS Name and Version
> * JDK Vendor and Version (shouldn't be interesting to us as we have the IDE info but just in case)
> * Last actionId (provided by `IdeaLogger#ourLastActionId`)
> 
> Attachments are currently not being sent as I am not sure about file size limits and other limitations we would be encountering in sentry.io.
