### ISSUE TITLE
Incompatible with PhpStorm 2024.3

### ISSUE THREAD

**Issue by AkibaAT** [php-perfect/ddev-intellij-plugin#379]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you sure that this bug is related to this DDEV Integration Plugin?

- [X] I am sure

### Describe the bug

The plugin is not compatible with 2024.3, currently available as EAP.

**Comment by AkibaAT** [comment]
Testbuild for 2024.3 Release Version: [ddev-intellij-plugin-0.0.1-dev.zip](https://github.com/user-attachments/files/17748235/ddev-intellij-plugin-0.0.1-dev.zip)
PR will follow once I've look into the open deprecation warnings.

**Comment by ayalon** [comment]
It would be awesome if you could release a new version :-)

**Comment by tame4tex** [comment]
Thanks for the fix @AkibaAT !

For anyone not sure what to do with the zip file above here are some basic instructions.

To install/update a plugin from the zip file downloaded above:
1. Download the zip file
2. Ensure the current ddev plugin is still enabled
3. Follow the instructions on https://www.jetbrains.com/help/phpstorm/managing-plugins.html#install_plugin_from_disk which will update the plugin to the version contained in the zip file.
