### ISSUE TITLE
Check Wording

### ISSUE THREAD

**Issue by nico-loeber** [php-perfect/ddev-intellij-plugin#48]
Wording of the DDEV Integration Plugins should be checked by a native english speaker.

The capitalization of Intellij must be respected.
https://jetbrains.design/intellij/text/capitalization/

In this file you can find any text that can appear in the user interface: https://github.com/php-perfect/ddev-intellij-plugin/blob/main/src/main/resources/messages/DdevIntegrationBundle.properties

**Comment by rfay** [comment]
I will report any English language problems I find in this issue. Or do a PR.

**Comment by nico-loeber** [comment]
Thank you very much for taking care of this, @rfay!
If you think that things can be explained more precisely, you are welcome to reword the texts.

**Comment by rfay** [comment]
* TYPO sate->state
* "DDEV enabled" might be better as  "DDEV-enabled"

![image](https://user-images.githubusercontent.com/112444/168449375-cd52e5a6-6f1c-49d4-82b3-aa96b6a8ca66.png)

**Comment by rfay** [comment]
My suggestions in
* https://github.com/php-perfect/ddev-intellij-plugin/pull/51

**Comment by nico-loeber** [comment]
Version 1.0 is now feature complete, probably...
This is a good time to finalize the wording of the messages: https://github.com/php-perfect/ddev-intellij-plugin/blob/main/src/main/resources/messages/DdevIntegrationBundle.properties
@rfay could you please take another look?

**Comment by rfay** [comment]
I read through it and it looks ok to me.

**Comment by nico-loeber** [comment]
> I read through it and it looks ok to me.

Thank you!
