### ISSUE TITLE
GitHub Actions: Re-enable jacoco coverage report

### ISSUE THREAD

**Issue by SpraxDev** [php-perfect/ddev-intellij-plugin#62]
When updating `org.jetbrains.intellij` in 8145a8605a969753540862b8fc7f6a27fd10923d (#59) the jacoco report generation started failing with the errors
> Caused by: : Error while creating report
> [...]
> Caused by: java.io.IOException: Error while analyzing /home/runner/work/ddev-intellij-plugin/ddev-intellij-plugin/build/classes/java/main/de/php_perfect/intellij/ddev/statusBar/DdevStatusBarWidgetFactoryImpl.class.
> [...]
> Caused by: java.lang.IllegalStateException: Can't add different class with same name: de/php_perfect/intellij/ddev/statusBar/DdevStatusBarWidgetFactoryImpl

This doesn't feel like an error on our side, so the commit ea6955a6bda37bf51e080b3bc568ef0b0fe59623 in (#59) should be reverted as soon as an update is available that fixes the issue.

- - -

Additionally the SonarCloud workflow should be re-enabled again. It keeps failing with OutOfMemory errors

**Comment by nico-loeber** [comment]
I guess the issue might be on our side, since it did no exists before merging the dependency updates.
The test report package was not updated. Maybe this might also have something to do with memory limits or other JVM configuration?

**Comment by nico-loeber** [comment]
The code coverage issue should be fixed now by
* https://github.com/php-perfect/ddev-intellij-plugin/pull/84

**Comment by SpraxDev** [comment]
Looks like there are still some issues. Could not get it to not detect 0% coverage and found a ticket about that.

I've subscribed to it and maybe they find something that needs to be configured or fixed in the intellij-plugin.

JetBrains/gradle-intellij-plugin#1065
