### ISSUE TITLE
Not found in marketplace, or not compatible

### ISSUE THREAD

**Issue by rfay** [php-perfect/ddev-intellij-plugin#79]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you sure that this bug is related to this DDEV Integration Plugin?

- [X] I am sure

### Describe the bug

I just went to test this again and again found it unavailable in marketplace. On https://plugins.jetbrains.com/plugin/18813-ddev-integration it shows "Not compatible":

<img width="1403" alt="image" src="https://user-images.githubusercontent.com/112444/176272750-c0aacee0-0b6e-47f7-aa1c-65c0d7d3c4a4.png">

If I search for "DDEV" in my PhpStorm->Plugins->Marketplace nothing shows up. PhpStorm 2022.1.3.

**Comment by nico-loeber** [comment]
I also noticed this. I'm quite sure the problem is that there is no compatible stable version yet. I think this is fixed when the stable version is published, so in a few days.

**Comment by rfay** [comment]
Maybe the README can be updated with a technique until then?

**Comment by nico-loeber** [comment]
> Maybe the README can be updated with a technique until then?

It is available now. :)
