### ISSUE TITLE
DDEV Commands Fail when the project is opend in PHPStorm

### ISSUE THREAD

**Issue by nico-loeber** [php-perfect/ddev-intellij-plugin#80]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you sure that this bug is related to this DDEV Integration Plugin?

- [ ] I am sure

### Describe the bug

On MacOS it may happen that DDEV commands like `ddev npx install` fail with file system errors (File not found, stat failed, ...) when the project is opend in PHPStorm with the DDEV Integration Plugin enabled.

### Steps to reproduce

1. Use MacOs
2.  Start PHPStorm
3. Open a ddev project
4. Run a ddev command on CLI like `ddev npx install`
5. Repeat executing the command a few times

**Comment by nico-loeber** [comment]
This is caused by an issue if 2 ddev commands run at the same time. You can avoid this issue by turning of "Watch DDEV state in background" in `File | Settings | Tools | DDEV Integration`.

Also there is already a fix available for DDEV that will be released soon.
- https://github.com/drud/ddev/pull/3946

**Comment by graham73may** [comment]
I was going to open a new bug, but I think maybe this one is related. 

Adding a bug report ID: e720eb89f0f64c4d93a151f036fe540e

**Comment by nico-loeber** [comment]
> Adding a bug report ID: e720eb89f0f64c4d93a151f036fe540e

> CommandFailedException de.php_perfect.intellij.ddev.cmd.DdevImpl in execute
Command timed out after 5 seconds: /usr/local/bin/ddev describe --json-output

I don't think a timeout can be related to this issue, as this issue is based on missing files in the file system when a ddev command is executed.

**Comment by nico-loeber** [comment]
Closing this issue as it was fixed in DDEV some time ago.
