### ISSUE TITLE
Can't find "DDEV Integration" in PhpStorm.

### ISSUE THREAD

**Issue by mikesnoeren** [php-perfect/ddev-intellij-plugin#85]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you sure that this bug is related to this DDEV Integration Plugin?

- [X] I am sure

### Describe the bug

Can't find the plugin on the PhpStorm plugin marketplace. 
Running on Build #PS-221.5591.58, built on May 12, 2022

![image](https://user-images.githubusercontent.com/52166423/178499474-eeb67f64-7236-4db9-8fb4-2164f7c0bacb.png)

I am aware I can install by going to the [Jetbrains Marketplace](https://plugins.jetbrains.com/plugin/18813-ddev-integration) but installing via IDE is much more convenient!

**Comment by nico-loeber** [comment]
Hello @mikesnoeren,

thanks for reporting this!

Your version seems a bit too old for the plugin to be installed. 
The minimum Version for the current stable release is 221.5787.
As soon as you update your IDE you should see the plugin in the marketplace.

Please give feedback if everything works as expected after updating, thanks!

**Comment by mikesnoeren** [comment]
Hi @nico-loeber,

I have updated my IDE to the latest version which solved my issue. 
Reason I wasn't up-to-date was because for some reason my IDE decided to not give me update notifications anymore..

Thanks for your help, great plugin!
