### ISSUE TITLE
Failure to set up phpunit ("Docker account not found")

### ISSUE THREAD

**Issue by rfay** [php-perfect/ddev-intellij-plugin#92]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you sure that this bug is related to this DDEV Integration Plugin?

- [ ] I am sure

### Describe the bug

I created a new project and opened it and wanted to set up phpunit.

1. Removed project .idea for a fresh start, `rm -r .idea`
2. Project running non-default php 8.1
3. `ddev start`
4. Opened PhpStorm 2022.2, ddev-intellij-plugin 1.0.1
5. Everything was all set up for me, along with a remote interpreter.

When I went to set up a test runner (phpunit) though, I had trouble. It wouldn't find phpunit and said instead "Docker account not found"

<img width="990" alt="Cursor_and_Preferences_and_d9" src="https://user-images.githubusercontent.com/112444/182975667-7854ef85-d593-4ed3-8fdf-7c0e3ddbb8bc.png">

After that I was able to go to the CLI interpreter page (set up by the plugin) and it showed php8.1 as not installed:

<img width="831" alt="Cursor_and_CLI_Interpreters_and_Preferences" src="https://user-images.githubusercontent.com/112444/182975854-0c0823e1-a9fe-4baf-9703-66a710f1515c.png">

So I changed the interpreter to just "php", which *should* be working because they actually fixed the problem now in 2022.2 that required you to *not* use just "php" and then it found everything correctly.

<img width="730" alt="Cursor_and_CLI_Interpreters" src="https://user-images.githubusercontent.com/112444/182975951-566da022-66c3-4d21-ab01-263a49a39c27.png">

Now if I go back to the test framework and refresh, it finds it and everything works:
<img width="744" alt="Notification_Center" src="https://user-images.githubusercontent.com/112444/182976007-5f5f77fb-510f-416c-8709-14e904dc8c22.png">

### Steps to reproduce

Above

### Additional context

I want to update https://ddev.readthedocs.io/en/latest/users/topics/phpstorm/ but would like this to get resolved before doing it.

* Require 2022.2
* Remove the section about having to use phpx.x
* Highly recommend at the top to "just use the plugin"

**Comment by nico-loeber** [comment]
Thanks for reporting this @rfay!
I will take a look at it asap. Do you have an idea why php8.1 is no longer working?
I would expect it to be still in PATH. The docker account error seems realy strange...

**Comment by rfay** [comment]
There are two things here.

1. The big deal is that there's no need to use "php8.1" any more, or "php5.6" or anything, because they fixed the bug in 2022.2 that used `docker-compose run` to evaluate this instead of `docker-compose exec`.
2. php8.1 is in fact in the PATH, and nothing has changed there.  But the plugin doesn't need to be doing that any more, and it's unnecessary complexity.

**Comment by rfay** [comment]
Just to make sure the link is here, the fixed PhpStorm issue is https://youtrack.jetbrains.com/issue/WI-62463 and it's fixed after a year, yay!

**Comment by nico-loeber** [comment]
Okay, I did some testing and found out that:

The "Docker account not found" error occured for me when opening an existing project created in PHPStorm 2021 in 2022.
The select option `Docker Compose > Server` was empty in this case. Manualy selecting "Docker" solved the issue.
Deleting the Interpreter does also solve the issue, as it is regenerated correctly by the plugin.
This might be an issue with the PHPStorm update, maybe there is a bc break in how the configuration is persisted or something like that but probably nothing I can fix in the plugin.
Please tell me if you can reproduce this issue for new projects and tell me how @rfay.

The php binary set to php8.1 does still work and shouldn't have any negative effect. I agree that setting the php version explicitly is no longer neccessary. As you should not need to edit the config on your own this is just cosmetics in my opinion.
The interpreter needs to be reconfigured on every php version change in ddev (detected on ddev start / restart) anyway, because PhpStorm needs to check the running php version and its extensions (xdebug).

**Comment by nico-loeber** [comment]
Is the environment variable `ddev-{projectName}` still needed?

I would love to remove it.
https://github.com/php-perfect/ddev-intellij-plugin/blob/9057376362610521d4f545160ce1840bb48541f9/src/main/java/de/php_perfect/intellij/ddev/php/PhpInterpreterProviderImpl.java#L102

I would schedule these changes for 1.1 as they should have no impact on the user and are only cosmetic / redundant.

**Comment by rfay** [comment]
This is just about https://docs.docker.com/compose/compose-file/#name-top-level-element - Probably for its whole history DDEV has relied on the env var, and not sure if the `name` element has always been there, but it would be better. I'd be fine with a PR to put `name` in app_compose_template.yaml and stop using the COMPOSE_PROJECT_NAME. It's about time.

**Comment by rfay** [comment]
Is there a correct way to completely wipe out anything PhpStorm might be doing? I did delete the project .idea, but I saw the "server" was still in there. Seemed to be just a name, but I'd rather have killed it.

**Comment by rfay** [comment]
A followup: I reset to factory defaults in PhpStorm 2022.2 using File->Manage IDE Settings->Restore default settings and started over again.

1. PHP Language Level defaults to 7.0, which I wouldn't expect. 
2. CLI interpreter is correctly set to DDEV but
    * In DDEV CLI interpreter the "Server" is blank
    * PHP Executable is set to php8.1, but it doesn't work, as described above.
    * Configuration file is blank
    * PHP Version "Not installed"
    * If you click "OK" at the bottom, you get "Docker server not selected"
    * If you click the refresh on PHP version you get "Docker account not specified"
3. If you create a new server (default name is Docker) using "Docker for Mac" with the defaults then everything works, and even the config file is detected. (Again, this should be using just "php", not "phpx.x" these days with PhpStorm 2022.2.
4. The Docker Tools configuration has a potentially inappropriate path for docker-compose, which is bundled with DDEV and is not otherwise required. It would be a lot better for it to use ~/.ddev/bin/docker-compose. I'll open a separate issue for that. 


<img width="985" alt="Cursor_and_Preferences_and_d9" src="https://user-images.githubusercontent.com/112444/185169515-8717fd92-a60e-47b9-a1d2-3e67fcb2c39c.png">

<img width="831" alt="Cursor_and_CLI_Interpreters_and_Preferences_and_d9" src="https://user-images.githubusercontent.com/112444/185169895-fae06d50-fd16-448f-9e0f-dd56a3d3b2e5.png">

**Comment by nico-loeber** [comment]
Thanks for the detailed information @rfay!

I was able to reproduce the issue that way.
The missing "Server" input is a reference to a "docker remote server". Such a server is generated by PHPStorm by default when there is none configured manually - at least sometimes.
In some situations, for example after restoring the default settings, this default server is missing.
I've added some code that will check for the existence of this server when configuring the php interpreter and if it does not, it will be generated with its default settings.

Thanks for pointing out this issue!

**Comment by rfay** [comment]
Oh, you're talking about PhpStorm's idea of a "Server", as described above (#3 in https://github.com/php-perfect/ddev-intellij-plugin/issues/92#issuecomment-1218126836). I was quite confused by your use of the words "docker remote server", as there's nothing here about "remote", and it has nothing to do with "setting up a server", it's just PhpStorm configuration of the Docker server. Terminology in #102 made me confused too, but I guess we're on the right track. And it's all PhpStorm's fault originally for using the term "server" without proper context.

* #102

**Comment by nico-loeber** [comment]
You are not the only one who is confused @rfay! It took me several hours to find out which entity I have to create to ensure the Docker "Server" is available. For PHPStorm it is a "RemoteServer" of the type "DockerCloud".

This should be fixed with the next release.
