### ISSUE TITLE
Use ~/.ddev/bin/docker-compose as the docker-compose tool in Tools->Docker

### ISSUE THREAD

**Issue by rfay** [php-perfect/ddev-intellij-plugin#95]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you sure that this bug is related to this DDEV Integration Plugin?

- [X] I am sure

### Describe the bug

Currently the plugin does not apparently change the path to the docker-compose binary. DDEV uses ~/.ddev/bin/docker-compose and does not otherwise require docker-compose to be installed on the system, and it may not be installed. But with the current setting (defaults to what's found in $PATH I think, often /usr/local/bin/docker-compose) it may mean that the plugin uses a different docker-compose than DDEV itself uses.

I recommend using the DDEV docker-compose from ~/.ddev/bin.

### Steps to reproduce

<img width="977" alt="Cursor_and_Preferences" src="https://user-images.githubusercontent.com/112444/185173787-d1741842-ed5a-49e0-8dfc-af8e11fdc863.png">

**Comment by mstrelan** [comment]
I would be cautious about changing the _globally_ configured docker compose executable. If this configuration is _project specific_ and the project uses ddev then this would be perfect.

**Comment by rfay** [comment]
IMO it's worth the minor risk, but it's a valid point @mstrelan

**Comment by nico-loeber** [comment]
Thanks for this proposal @rfay and sorry for my late reply.
As @mstrelan already said this is a global setting. Changing it automatically would affect all your projects wihtout your knowledge. You would also need to enable the "Use Compose V2" setting as ddev is using v2 format. This would make any non ddev compose v1 projects unusable.

Also the situation is a bit more complex if you are using WSL. Projects located in Windows need a compose binary located in your windows but probably you don't even have ddev installed on your windows file system if you are a WSL user.

As long as there is no project specific setting we can not touch this.

**Comment by rfay** [comment]
You're not entirely correct.

PhpStorm's "Use Compose V2" is actually misnamed. It actually tells PhpStorm to use `docker compose` instead of `docker-compose`, which we do not need to do, and that does not need to be checked for DDEV at all. 

I do find that there seems to be no way to get PhpStorm to use docker-compose inside WSL2, which is a pretty serious problem.

I recommend that the Plugin check to make sure that docker-compose is at least a usable version, or there will be lots of interesting behavior. With current DDEV v1.21.1, docker-compose v1 is no longer supported, but some people still have "Use dockeer-compose v1" set in their Docker Desktop.

This class of problem should be addressed one way or another in the plugin.
